version: '2.1'
services:
    mysql.cmw:
        container_name: ${CMW_MYSQL_CONTAINER:-mysql.cmw}
        image: mysql:5.7
        platform: linux/amd64
        volumes:
            - ./_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: dev
        networks:
          - default

    wp.cmw:
        container_name: ${CMW_WP_CONTAINER:-wp.cmw}
        image: wordpress:5.5.1-php7.4-apache
        platform: linux/amd64
        volumes:
          - ./wp-content:/var/www/html/wp-content:rw,cached
          - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        expose:
          - '${CMW_PORT_BACKEND:-3080}'
        ports:
          - '${CMW_PORT_BACKEND:-3080}:80'
        environment:
          WORDPRESS_DB_HOST: ${CMW_MYSQL_CONTAINER:-mysql.cmw}:3306
          WORDPRESS_DB_NAME: cmw
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: dev
          WORDPRESS_CONFIG_EXTRA: |
            define('WP_SITEURL', '${WP_SITEURL:-http://localhost:3080}' );
            define('WP_HOME', '${WP_HOME:-http://localhost:3080}' );
        networks:
          - default

networks:
    default:
